// Generated by wxt
import "wxt/browser";

declare module "wxt/browser" {
  export type PublicPath =
    | "/"
    | "/avatar.png"
    | "/background.js"
    | "/content-scripts/content.js"
    | "/hammy-face.png"
    | "/icon-128.png"
    | "/icon-16.png"
    | "/icon-48.png"
    | "/options.html"
    | "/popup.html"
    | "/videos/hammy-breathe.webm"
    | "/videos/hammy-drink-water.webm"
    | "/videos/hammy-eye-break.webm"
    | "/videos/hammy-posture.webm"
    | "/videos/hammy-stretch.webm"
  type HtmlPublicPath = Extract<PublicPath, `${string}.html`>
  export interface WxtRuntime {
    getURL(path: PublicPath): string;
    getURL(path: `${HtmlPublicPath}${string}`): string;
  }
}
